on:
  issues:
    types:
      - labeled
      - edited
    
jobs:
  process_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: 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
      - uses: ./
        with:
          token: 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
          publish-label: 'good'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update markdown from gh issue'