on:
  workflow_dispatch:
  issues:
    types:
      - labeled
      - edited
    
jobs:
  process_issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.ACCESS_TOKEN}}
      - uses: ./
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          publish-label: 'good'
          src-repo: 'Verilog-Solutions/report-swaylend-20230224'
          batch: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update markdown from gh issue'